[build]
  publish = "."

[[redirects]]
  from   = "/admin/config.yml"
  to     = "/admin/config.yml"
  status = 200

[[redirects]]
  from   = "/admin/index.html"
  to     = "/admin/index.html"
  status = 200

[[redirects]]
  from   = "/admin"
  to     = "/admin/index.html"
  status = 200

[[redirects]]
  from   = "/admin/*"
  to     = "/admin/index.html"
  status = 200
  force  = true
