[build]
  # žiadny build command, lebo je to čistý HTML projekt
  publish = "."      # <-- toto hovorí Netlify: „Hľadaj index.html aj _redirects tu, v root“

[[redirects]]
  from   = "/admin"
  to     = "/admin/index.html"
  status = 200
  force  = true

[[redirects]]
  from   = "/admin/*"
  to     = "/admin/index.html"
  status = 200
  force  = true
