[build]
  publish = "."    # Ensure we publish from the repo root

# Serve the raw CMS config & index:
[[redirects]]
  from   = "/admin/config.yml"
  to     = "/admin/config.yml"
  status = 200

[[redirects]]
  from   = "/admin/index.html"
  to     = "/admin/index.html"
  status = 200

# Everything else under /admin → serve the SPA loader
[[redirects]]
  from   = "/admin/*"
  to     = "/admin/index.html"
  status = 200
  force  = true
