
backend:
  name: github
  repo: AdamMacejka/FestClassicRockBand  # exactly your GitHub repo name
  branch: main
  auth_scope: "repo"
  app_id: "0v23liQrIQsMirq3NKbx"
media_folder: "images/uploads"
public_folder: "/images/uploads"

# if you don’t have an Uploadcare key, you can omit this block,
# but newer Netlify CMS versions sometimes require a stub:
media_library:
  name: uploadcare
  config:
    publicKey: "demopublickey"

collections:
  - name: "about"
    label: "O nás"
    files:
      - label: "Text sekcie O nás"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Obsah", name: "body", widget: "markdown" }

  - name: "members"
    label: "Členovia"
    folder: "content/members"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Meno",       name: "title",       widget: "string" }   # ← zmena tu
      - { label: "Nástroj",    name: "instrument", widget: "string" }
      - { label: "Fotka",      name: "image",      widget: "image" }

  - name: "concerts"
    label: "Koncerty"
    folder: "content/concerts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Dátum",   name: "date",     widget: "datetime" }
      - { label: "Miesto",  name: "location", widget: "string" }
