
backend:
  name: test-repo
  local_backend: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "about"
    label: "O nás"
    files:
      - label: "Text sekcie O nás"
        name: "about_text"
        file: "content/about.md"
        fields:
          - { label: "Text", name: "body", widget: "markdown" }

  - name: "members"
    label: "Členovia"
    label_singular: "Člen"
    folder: "content/members"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Meno", name: "title", widget: "string" }
      - { label: "Nástroj", name: "instrument", widget: "string" }
      - { label: "Fotka", name: "image", widget: "image" }

  - name: "concerts"
    label: "Koncerty"
    folder: "content/concerts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Dátum", name: "date", widget: "datetime" }
      - { label: "Miesto", name: "location", widget: "string" }
