
backend:
  name: github
  repo: tvoje‑user/fest-classic-rock-band
  branch: main
  auth_scope: "repo"
  app_id: "${GITHUB_CLIENT_ID}"

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "about"
    label: "O nás"
    files:
      - label: "Text sekcie O nás"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Text", name: "body", widget: "markdown" }

  - name: "members"
    label: "Členovia"
    folder: "content/members"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Meno", name: "name", widget: "string" }
      - { label: "Nástroj", name: "instrument", widget: "string" }
      - { label: "Fotka", name: "image", widget: "image" }

  - name: "concerts"
    label: "Koncerty"
    folder: "content/concerts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Dátum", name: "date", widget: "datetime" }
      - { label: "Miesto", name: "location", widget: "string" }
