backend:
  name: github
  repo: AdamMacejka/FestClassicRockBand
  branch: main
  auth_scope: "repo"
  app_id: "${GITHUB_CLIENT_ID}"  # pre debug môžeš natvrdo: "0v23liQrIQsMirq3NKbx"

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "about"
    label: "O nás"
    files:
      - label: "Text sekcie O nás"
        name: "about"
        file: "content/about.md"
        fields:
          - label: "Obsah"
            name: "body"
            widget: "markdown"

  - name: "homepage"
    label: "Úvodná stránka"
    files:
      - label: "Hlavná stránka"
        name: "homepage"
        file: "content/homepage.yml"
        fields:
          - { label: "Názov kapely", name: "band_name", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string", required: false }
          - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
          - { label: "Placeholder Image", name: "placeholder_image", widget: "image", required: false }
          - { label: "Logo (na cover)", name: "logo_image", widget: "image", required: false }
          - { label: "O nás", name: "about_text", widget: "markdown", required: false }
          - { label: "Email", name: "contact_email", widget: "string", required: false }
          - { label: "Facebook URL", name: "facebook_url", widget: "string", required: false }



  - name: "members"
    label: "Členovia"
    folder: "content/members"
    create: true
    slug: "{{slug}}"
    identifier_field: "name"
    fields:
      - { label: "Meno", name: "name", widget: "string" }
      - { label: "Nástroj", name: "instrument", widget: "string" }
      - { label: "Fotka", name: "image", widget: "image" }

  - name: "concerts"
    label: "Koncerty"
    folder: "content/concerts"
    create: true
    slug: "{{slug}}"
    identifier_field: "date"
    fields:
      - { label: "Dátum", name: "date", widget: "datetime" }
      - { label: "Miesto", name: "location", widget: "string" }
